modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"
[[mods]]
modId="ichthyology"
version="1.0.0"
displayName="Ichthyology"
credits="${mod_authors}"
description='''
${mod_description}
'''
[[dependencies.ichthyology]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ichthyology]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    